### ISSUE TITLE
Details on hardware required

### ISSUE THREAD

**Issue by ioExpander** [raziel83257/micronovaEsphome#1]
Hi found this repo because I'm looking into controlling my Pellet Stove from Jolly Mec (using a Micronova board) using ESPHome. Does your project work ? Can you please share some details on the wiring and physical setup you are using ? Thank you.

**Comment by raziel83257** [comment]
I've used this schema from @philibertc
![image](https://github.com/raziel83257/micronovaEsphome/assets/9800701/0cc263d6-3f9a-4fb3-ba20-fd2ae8db5124)

**Comment by ioExpander** [comment]
Thank you. This uses an Enable_RX pin but I don't see how you are using this in your code (yml or .h). Is the main branch currently working ? I see you made recent commits so maybe this is just work in progress. I might be able to contribute.

**Comment by raziel83257** [comment]
Now I no longer have that stove but I can confirm that it worked, unfortunately I can't find the board I used, as soon as I find it I'll post the photos.
I've updated the YAML and .h cause I found it was old comparing what I have on my homeassistant.

**Comment by raziel83257** [comment]
> Thank you. This uses an Enable_RX pin but I don't see how you are using this in your code (yml or .h). Is the main branch currently working ? I see you made recent commits so maybe this is just work in progress. I might be able to contribute.

You are right, in the end I've used a simpler scheme in half duplex, I think it was this:
![image](https://github.com/raziel83257/micronovaEsphome/assets/9800701/93cbcab0-cac4-4a05-b5f6-810ac4cfca04)
![20230629_083708536_iOS](https://github.com/raziel83257/micronovaEsphome/assets/9800701/4298690d-11b3-4f4a-8d82-26e924c181a7)

https://embedds.com/half-duplex-uart-from-single-avr-pin/


I remember that the d1 mini takes GND and 5v directly from the serial of the micronova
![20230629_083758015_iOS](https://github.com/raziel83257/micronovaEsphome/assets/9800701/ae11601a-0c6d-4ae7-9bd8-5e2b72a44fa0)
